import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import ThemeRegistry from '../utils/ThemeRegistry'
import { Inter } from 'next/font/google';

import Sidebar from '../components/Sidebar';
import "./globals.css";

const inter = Inter({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
  pageProps
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <AppRouterCacheProvider>
          <ThemeRegistry options={{ key: 'mui-theme' }} {...pageProps}>
            <Sidebar>
              {children}
            </Sidebar>
          </ThemeRegistry>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}